# conda_recipe/meta.yaml

package:
  name: login_automation
  version: "0.1.0"

source:
  path: ..

build:
  script: python -m pip install .
  environment:
    file: environment.yaml

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pip
    
test:
  commands:
    - pytest

about:
  home: https://github.com/OzMaatuk/LoginAutomation
  license: MIT
  summary: A project to automate login to different sites.